# Generated by Django 5.0.1 on 2024-02-28 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentPanel', '0002_student_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='username',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
