# Generated by Django 5.0.1 on 2024-02-09 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentPanel', '0002_remove_demo_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='demo',
        ),
    ]
