# Generated by Django 5.0.1 on 2024-02-17 10:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentPanel', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='userId',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
