# Generated by Django 5.0.1 on 2024-02-17 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0001_initial'),
        ('facultyPanel', '0002_alter_faculty_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
