# Generated by Django 5.0.1 on 2024-02-17 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userAuth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accountant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(max_length=100)),
                ('joining_date', models.DateField()),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='userAuth.person')),
            ],
        ),
    ]
