# Generated by Django 5.0.1 on 2024-02-27 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userAuth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accountant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=100, unique=True)),
                ('qualification', models.CharField(max_length=100)),
                ('joining_date', models.DateField()),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='userAuth.person')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transID', models.CharField(max_length=100, unique=True)),
                ('amount', models.IntegerField()),
                ('payment_type', models.CharField(max_length=100)),
                ('chequeNo', models.IntegerField()),
                ('time', models.TimeField()),
                ('semester', models.IntegerField()),
                ('accountant', models.ManyToManyField(to='acPanel.accountant')),
            ],
        ),
    ]
