# Generated by Django 5.0.2 on 2024-03-24 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acPanel', '0005_payment_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
