# Generated by Django 5.0.2 on 2024-04-01 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acPanel', '0009_alter_payment_chequeno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='chequeNo',
            field=models.IntegerField(null=True),
        ),
    ]
