# Generated by Django 5.0.1 on 2024-02-28 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultyPanel', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='username',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
