# Generated by Django 5.0.2 on 2024-02-29 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facultyPanel', '0004_announcement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='programe',
            new_name='program',
        ),
    ]
