# Generated by Django 5.0.2 on 2024-02-29 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultyPanel', '0005_rename_programe_subject_program'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mark',
            old_name='obtainmarks',
            new_name='obtained_marks',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='refrencebook',
            new_name='reference_book',
        ),
        migrations.RemoveField(
            model_name='exampaper',
            name='paperid',
        ),
        migrations.RemoveField(
            model_name='hallticket',
            name='hallticketid',
        ),
        migrations.RemoveField(
            model_name='program',
            name='departmentID',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='departmentid',
        ),
        migrations.AddField(
            model_name='program',
            name='department_name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
