# Generated by Django 5.0.2 on 2024-03-01 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultyPanel', '0006_rename_obtainmarks_mark_obtained_marks_and_more'),
        ('studentPanel', '0003_alter_student_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_hours', models.IntegerField(blank=True, null=True)),
                ('present_hours', models.IntegerField(blank=True, null=True)),
                ('upload_date', models.DateField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentPanel.student')),
            ],
        ),
    ]
