# Generated by Django 5.0.2 on 2024-03-01 05:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultyPanel', '0008_alter_attendancerecord_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='upload_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 1, 5, 19, 43, 951329, tzinfo=datetime.timezone.utc)),
        ),
    ]
