# Generated by Django 5.0.2 on 2024-03-10 16:58

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultyPanel', '0013_alter_attendancerecord_upload_date'),
        ('studentPanel', '0003_alter_student_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='upload_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 10, 16, 58, 16, 788662, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='hallticket',
            name='program',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='facultyPanel.program'),
        ),
        migrations.RemoveField(
            model_name='hallticket',
            name='student',
        ),
        migrations.AddField(
            model_name='hallticket',
            name='student',
            field=models.ManyToManyField(to='studentPanel.student'),
        ),
    ]
