# Generated by Django 5.0.2 on 2024-03-10 19:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultyPanel', '0017_alter_attendancerecord_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='upload_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 10, 19, 9, 13, 263707, tzinfo=datetime.timezone.utc)),
        ),
        migrations.RemoveField(
            model_name='hallticket',
            name='program',
        ),
        migrations.AddField(
            model_name='hallticket',
            name='program',
            field=models.ManyToManyField(to='facultyPanel.program'),
        ),
    ]
