# Generated by Django 5.0.2 on 2024-03-24 15:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultyPanel', '0018_alter_attendancerecord_upload_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='upload_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 24, 15, 35, 17, 848995, tzinfo=datetime.timezone.utc)),
        ),
    ]
