# Generated by Django 5.0.2 on 2024-03-24 17:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultyPanel', '0021_alter_attendancerecord_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='upload_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 24, 17, 6, 25, 501391, tzinfo=datetime.timezone.utc)),
        ),
    ]
