# Generated by Django 5.0.2 on 2024-03-30 17:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultyPanel', '0022_alter_attendancerecord_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='upload_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 30, 17, 37, 26, 156010, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='ExamPaper',
        ),
    ]
