# Generated by Django 5.0.2 on 2024-03-30 17:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultyPanel', '0023_alter_attendancerecord_upload_date_delete_exampaper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='upload_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 30, 17, 59, 0, 363780, tzinfo=datetime.timezone.utc)),
        ),
    ]
