# Generated by Django 5.0.2 on 2024-03-31 15:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultyPanel', '0024_alter_attendancerecord_upload_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='department',
            field=models.CharField(default='CE', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='upload_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 31, 15, 0, 6, 424916, tzinfo=datetime.timezone.utc)),
        ),
    ]
