# Generated by Django 5.0.2 on 2024-03-31 16:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultyPanel', '0025_faculty_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='upload_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 31, 16, 33, 29, 337441, tzinfo=datetime.timezone.utc)),
        ),
    ]
