# Generated by Django 5.0.2 on 2024-04-01 04:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultyPanel', '0037_alter_attendancerecord_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='upload_date',
            field=models.DateField(default=datetime.datetime(2024, 4, 1, 4, 23, 32, 126205, tzinfo=datetime.timezone.utc)),
        ),
        migrations.RemoveField(
            model_name='mark',
            name='subject',
        ),
        migrations.AddField(
            model_name='mark',
            name='subject',
            field=models.ManyToManyField(to='facultyPanel.subject'),
        ),
    ]
