# Generated by Django 5.0.2 on 2024-04-01 04:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultyPanel', '0038_alter_attendancerecord_upload_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='upload_date',
            field=models.DateField(default=datetime.datetime(2024, 4, 1, 4, 53, 16, 921600, tzinfo=datetime.timezone.utc)),
        ),
    ]
