# Generated by Django 5.0.2 on 2024-04-01 05:41

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultyPanel', '0039_alter_attendancerecord_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='upload_date',
            field=models.DateField(default=datetime.datetime(2024, 4, 1, 5, 41, 31, 763369, tzinfo=datetime.timezone.utc)),
        ),
        migrations.RemoveField(
            model_name='mark',
            name='subject',
        ),
        migrations.AddField(
            model_name='mark',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='facultyPanel.subject'),
            preserve_default=False,
        ),
    ]
