# Generated by Django 5.0.2 on 2024-04-01 08:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultyPanel', '0040_alter_attendancerecord_upload_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='upload_date',
            field=models.DateField(default=datetime.datetime(2024, 4, 1, 8, 6, 34, 880957, tzinfo=datetime.timezone.utc)),
        ),
    ]
