# Generated by Django 5.0.1 on 2024-02-27 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facultyPanel', '0002_initial'),
        ('studentPanel', '0001_initial'),
        ('userAuth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=100, unique=True)),
                ('qualification', models.CharField(max_length=100)),
                ('joining_date', models.DateField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='userAuth.person')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventID', models.IntegerField()),
                ('eventname', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('starttime', models.DateField()),
                ('duration', models.DurationField()),
                ('hod', models.ManyToManyField(to='managementPanel.hod')),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clubid', models.IntegerField()),
                ('clubname', models.CharField(max_length=100)),
                ('estdate', models.DateField()),
                ('type', models.CharField(max_length=100)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facultyPanel.faculty')),
                ('student', models.ManyToManyField(to='studentPanel.student')),
                ('hod', models.ManyToManyField(to='managementPanel.hod')),
            ],
        ),
    ]
