# Generated by Django 5.0.1 on 2024-02-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementPanel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hod',
            name='userId',
            field=models.CharField(default=-1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
