# Generated by Django 5.0.2 on 2024-03-24 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementPanel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hod',
            name='person',
        ),
        migrations.RemoveField(
            model_name='hod',
            name='userId',
        ),
        migrations.AddField(
            model_name='hod',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hod',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='hod',
            name='username',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
