# Generated by Django 5.0.2 on 2024-04-01 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementPanel', '0003_delete_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='hod',
            name='date_of_birth',
            field=models.DateField(default='2004-10-04'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hod',
            name='last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
