# Generated by Django 5.0.2 on 2024-04-01 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managementPanel', '0005_remove_hod_date_of_birth_remove_hod_last_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
