# Generated by Django 5.0.2 on 2024-04-01 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementPanel', '0006_delete_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='hod',
            name='last_name',
            field=models.CharField(default='yyu', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hod',
            name='profile_pic',
            field=models.ImageField(default='static/default_profile.jpeg', upload_to='profile_pics'),
        ),
    ]
