# Generated by Django 5.0.2 on 2024-04-01 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementPanel', '0007_hod_last_name_hod_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='hod',
            name='date_of_birth',
            field=models.DateField(default='2002-10-12', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hod',
            name='email',
            field=models.EmailField(default='abc@gmail.com', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hod',
            name='gender',
            field=models.CharField(default='male', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hod',
            name='profile_pic',
            field=models.ImageField(default='default_profile.jpeg', upload_to='profile_pics'),
        ),
    ]
