# Generated by Django 5.0.1 on 2024-02-17 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='aadhar_number',
        ),
        migrations.RemoveField(
            model_name='person',
            name='annual_income',
        ),
        migrations.RemoveField(
            model_name='person',
            name='birth_date',
        ),
    ]
