# Generated by Django 5.0.1 on 2024-02-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0003_remove_person_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='profile_pic',
            field=models.ImageField(default=-1, upload_to='profile_pics'),
            preserve_default=False,
        ),
    ]
